# Generated by Django 3.2.12 on 2023-02-07 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EHRConnection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_name', models.CharField(max_length=250)),
                ('ehr_name', models.CharField(choices=[('epic', 'EPIC')], max_length=255)),
                ('app_type', models.CharField(choices=[('provider', 'Provider Facing Application'), ('patient', 'Patient Facing Application'), ('system', 'Backend System')], max_length=255)),
                ('grant_type', models.CharField(blank=True, choices=[('client_credentials', 'Client Credentials'), ('authorization_code', 'Authorization Code')], max_length=255, null=True)),
                ('client_id', models.CharField(max_length=250, unique=True)),
                ('client_secret', models.CharField(blank=True, max_length=250, null=True)),
                ('redirect_uri', models.URLField(blank=True, max_length=255, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('audiance', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('nonce', models.CharField(blank=True, max_length=255, null=True)),
                ('launch', models.CharField(blank=True, max_length=255, null=True)),
                ('base_url_test', models.URLField(blank=True, max_length=250, null=True)),
                ('base_url_prod', models.URLField(blank=True, max_length=250, null=True)),
                ('auth_url_test', models.URLField(blank=True, max_length=250, null=True)),
                ('auth_url_prod', models.URLField(blank=True, max_length=250, null=True)),
                ('authorize_url_test', models.URLField(blank=True, max_length=255, null=True)),
                ('authorize_url_prod', models.URLField(blank=True, max_length=255, null=True)),
                ('customer_auth_url_test', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('customer_auth_url_prod', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('access_token', models.TextField(blank=True, null=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('tenant', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(blank=True, max_length=250, null=True)),
                ('lastname', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('ehr_id', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('authorize_code', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('refresh_token_last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('ehr_id', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('authorize_code', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('refresh_token_last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='connection',
            field=models.ManyToManyField(blank=True, null=True, to='core.EHRConnection'),
        ),
    ]
