from enum import Enum
from tkinter import SEPARATOR
from tkinter.tix import IMMEDIATE

class Country(str, Enum):
    AF = "AF"
    AX = "AX"
    AL = "AL"
    DZ = "DZ"
    AS = "AS"
    AD = "AD"
    AO = "AO"
    AI = "AI"
    AQ = "AQ"
    AG = "AG"
    AR = "AR"
    AM = "AM"
    AW = "AW"
    AU = "AU"
    AT = "AT"
    AZ = "AZ"
    BS = "BS"
    BH = "BH"
    BD = "BD"
    BB = "BB"
    BY = "BY"
    BE = "BE"
    BZ = "BZ"
    BJ = "BJ"
    BM = "BM"
    BT = "BT"
    BO = "BO"
    IO = "IO"
    CM = "CM"
    CL = "CL"
    CO = "CO"
    CI = "CI"
    DK = "DK"
    EC = "EC"
    ER = "ER"
    FK = "FK"
    TF = "TF"
    GM = "GM"
    GI = "GI"
    GW = "GW"
    VA = "VA"
    IS = "IS"
    IM = "IM"
    JP = "JP"
    KI = "KI"
    LS = "LS"
    LT = "LT"
    MK = "MK"
    MV = "MV"
    MX = "MX"
    MS = "MS"
    NA = "NA"
    NC = "NC"
    MP = "MP"
    PK = "PK"
    PG = "PG"
    PL = "PL"
    RU = "RU"
    PM = "PM"
    SA = "SA"
    SG = "SG"
    SB = "SB"
    SS = "SS"
    SE = "SE"
    TZ = "TZ"
    TO = "TO"
    TV = "TV"
    US = "US"
    VN = "VN"
    EH = "EH"
    ZW = "ZW"
    BQ = "BQ"
    BR = "BR"
    BF = "BF"
    CA = "CA"
    TD = "TD"
    KM = "KM"
    CK = "CK"
    CU = "CU"
    DO = "DO"
    EE = "EE"
    FI = "FI"
    GE = "GE"
    GL = "GL"
    GN = "GN"
    GY = "GY"
    IN = "IN"
    IE = "IE"
    JE = "JE"
    KW = "KW"
    LB = "LB"
    LY = "LY"
    MO = "MO"
    ML = "ML"
    MR = "MR"
    MN = "MN"
    MM = "MM"
    NZ = "NZ"
    NU = "NU"
    OM = "OM"
    PY = "PY"
    PT = "PT"
    RO = "RO"
    KN = "KN"
    SN = "SN"
    RS = "RS"
    ZA = "ZA"
    LK = "LK"
    SJ = "SJ"
    SY = "SY"
    TK = "TK"
    TM = "TM"
    UG = "UG"
    UM = "UM"
    UZ = "UZ"
    WF = "WF"
    BA = "BA"
    BG = "BG"
    CV = "CV"
    CX = "CX"
    CD = "CD"
    CW = "CW"
    DJ = "DJ"
    GQ = "GQ"
    FO = "FO"
    PF = "PF"
    DE = "DE"
    GD = "GD"
    GG = "GG"
    HT = "HT"
    HK = "HK"
    IR = "IR"
    IL = "IL"
    KE = "KE"
    KG = "KG"
    LU = "LU"
    MY = "MY"
    MT = "MT"
    MU = "MU"
    ME = "ME"
    MZ = "MZ"
    NP = "NP"
    NF = "NF"
    PW = "PW"
    PH = "PH"
    QA = "QA"
    BL = "BL"
    MF = "MF"
    ST = "ST"
    SX = "SX"
    SI = "SI"
    GS = "GS"
    SR = "SR"
    TJ = "TJ"
    TG = "TG"
    TN = "TN"
    UA = "UA"
    VU = "VU"
    VG = "VG"
    BW = "BW"
    BN = "BN"
    KH = "KH"
    KY = "KY"
    CC = "CC"
    CR = "CR"
    CY = "CY"
    EG = "EG"
    FJ = "FJ"
    FR = "FR"
    GH = "GH"
    GP = "GP"
    GU = "GU"
    HN = "HN"
    IQ = "IQ"
    JM = "JM"
    KZ = "KZ"
    KP = "KP"
    LA = "LA"
    LR = "LR"
    MW = "MW"
    MH = "MH"
    YT = "YT"
    MD = "MD"
    MA = "MA"
    NI = "NI"
    NG = "NG"
    NO = "NO"
    PA = "PA"
    PN = "PN"
    RE = "RE"
    RW = "RW"
    LC = "LC"
    SM = "SM"
    SC = "SC"
    SK = "SK"
    ES = "ES"
    CH = "CH"
    TH = "TH"
    TT = "TT"
    TR = "TR"
    GB = "GB"
    VE = "VE"
    VI = "VI"
    ZM = "ZM"
    BV = "BV"
    BI = "BI"
    CF = "CF"
    CN = "CN"
    CG = "CG"
    HR = "HR"
    CZ = "CZ"
    DM = "DM"
    SV = "SV"
    ET = "ET"
    GF = "GF"
    GA = "GA"
    GR = "GR"
    GT = "GT"
    HM = "HM"
    HU = "HU"
    ID = "ID"
    IT = "IT"
    JO = "JO"
    KR = "KR"
    LV = "LV"
    LI = "LI"
    MG = "MG"
    MQ = "MQ"
    FM = "FM"
    MC = "MC"
    NR = "NR"
    NL = "NL"
    NE = "NE"
    PS = "PS"
    PE = "PE"
    PR = "PR"
    SH = "SH"
    VC = "VC"
    WS = "WS"
    SL = "SL"
    SO = "SO"
    SD = "SD"
    SZ = "SZ"
    TW = "TW"
    TL = "TL"
    TC = "TC"
    AE = "AE"
    UY = "UY"
    YE = "YE"

class Gender(str, Enum):
    FEMALE = "Female"
    MALE = "Male"
    UNKNOWN = "Unknown"
    OTHER = "Other"
    NONBINARY = "Nonbinary"

class Race(str, Enum):
    AMERICAN = "American Indian or Alaska Native",
    ASIAN = "Asian",
    BLACK = "Black or African American",
    HAWAIIAN = "Native Hawaiian or Other Pacific Islander",
    OTHER = "Other Race",
    WHITEL = "White",
    UNKNOWN = "Unknown"    


class RELIGION(str, Enum):
    LATTER_DAY_SAINTS = "Latter Day Saints",
    LUTHERAN = "Lutheran",
    MAHAYANA = "Mahayana",
    MEDITATION = "Meditation",
    MESSIANIC_JUDAISM = "Messianic Judaism",
    MITRASIM = "Mitraism",
    NEW_AGE = "New Age",
    NON_ROMAN_CATHOLIC = "non-Roman Catholic",
    OCCULT = "Occult",
    ADVENTIST = "Adventist",
    AFRICAN_RELIGIONS = "African Religions",
    AFRO_CARIBBEAN_RELIGIONS = "Afro-Caribbean Religions",
    AGNOSTICISM = "Agnosticism",
    ANGLICAN = "Anglican",
    ANIMISM = "Animism",
    ATHEISM = "Atheism",
    BABI_BAHA = "Babi & Baha'I faiths",
    BAPTIST = "Baptist",
    BON = "Bon",
    CAO_DAI= "Cao Dai",
    CELTICISM = "Celticism",
    CHRISTIAN = "Christian",
    CONFUCIANISM = "Confucianism",
    CYBERCULTURE_RELIGIONS = "Cyberculture Religions",
    DIVINATION = "Divination",
    FOURTH_WAY = "Fourth Way",
    FREE_DAISM = "Free Daism",
    GNOSIS = "Gnosis",
    HINDUISM = "Hinduism",
    HUMANISM = "Humanism",
    INDEPENDENT = "Independent",
    ISLAM = "Islam",
    JAINISM = "Jainism",
    JEHOVAHS_WITNESSES = "Jehovah's Witnesses",
    JUDAISM = "Judaism",
    ORTHODOX = "Orthodox",
    PAGANISM = "Paganism",
    PENTECOSTAL = "Pentecostal",
    REFORMED_PRESBYTERIAN = "Reformed/Presbyterian",
    ROMAN_CATHOLIC_CHURCH = "Roman Catholic Church",
    SATANISM = "Satanism",
    SCIENTOLOGY = "Scientology",
    SHAMANISM = "Shamanism",
    SHIITE = "Shiite (Islam)",
    SHINTO = "Shinto",
    SIKISM = "Sikism",
    SPIRITUALISM = "Spiritualism",
    SUNNI = "Sunni (Islam)",
    TAOISM = "Taoism",
    THERAVADA = "Theravada",
    UNITARIAN_UNIVERSALISM = "Unitarian-Universalism",
    UNIVERSAL_LIFE_CHURCH = "Universal Life Church",
    VAJRAYANA = "Vajrayana (Tibetan)",
    VEDA = "Veda",
    VOODOO = "Voodoo",
    WICCA = "Wicca",
    YAOHUSHUA = "Yaohushua",
    ZEN_BUDDHISM = "Zen Buddhism",
    Zoroastrianism = "Zoroastrianism",
    ASSEMBLY_OF_GOD = "Assembly of God",
    BRETHREN = "Brethren",
    CHRISTIAN_SCIENTIST = "Christian Scientist",
    CHURCH_OF_CHRIST = "Church of Christ",
    CHURCH_OF_GOD = "Church of God",
    CONGREGATIONAL = "Congregational",
    DISCIPLES_OF_CHRIST = "Disciples of Christ",
    EASTERN_ORTHODOX = "Eastern Orthodox",
    EPISCOPALIAN = "Episcopalian",
    EVANGELICAL_COVENANT = "Evangelical Covenant",
    FRIENDS = "Friends",
    FULL_GOSPEL = "Full Gospel",
    METHODIST = "Methodist",
    NATIVE_AMERICAN = "Native American",
    NAZARENE = "Nazarene",
    PRESBYTERIAN = "Presbyterian",
    PROTESTANT = "Protestant",
    REFORMED = "Reformed",
    SALVATION_ARMY = "Salvation Army",
    UNITARIAN_UNIVERSALIST = "Unitarian Universalist",
    UNITED_CHURCH_OF_CHRIST = "United Church of Christ",
    PROTESTANT_NO_DENOMINATION = "Protestant - No Denomination",
    PROCESS = "The Process",
    NONE = "None",
    OTHER = "Other",
    UNKNOWN = "Unknown"



class MARITAL_STATUS(str,Enum):
    SEPARATED = "Separated",
    UNMARRIED = "Unmarried",
    COMMON_LAW = "Common law",
    DIVORCED = "Divorced",
    LEGALLY_SEPARATED = "Legally Separated",
    LIVING_TOGETHER = "Living together",
    INTERLOCUTORY  = "Interlocutory",
    MARRIED = "Married",
    ANNULLED = "Annulled",
    OTHER = "Other",
    DOMESTIC_PARTNER = "Domestic partner",
    REGISTERED_DOMESTIC_PARTNER = "Registered domestic partner",
    SINGLE = "Single",
    UNREPORTED = "Unreported",
    UNKNOWN = "Unknown",
    WINOWED = "Widowed"

class PCP_TYPE(str, Enum):
    REFERRED_TO_PROVIDER = "Referred To Provider",
    REFERRING_PROVIDER = "Referring Provider", 
    PATIENT_PCP = "Patient PCP",
    OTHER = "Other"

class AUTHOR_TYPE(str, Enum):
    REFERRED_TO_PROVIDER  = "Referred To Provider",
    REFERRING_PROVIDER = "Referring Provider", 
    PATIENT_PCP = "Patient PCP",
    OTHER = "Other"

class PRIORITY(str,Enum):
    ONE = 1, 
    TWO = 2, 
    THREE = 3, 
    FOUR = 4

class COVERATE_TYPE(str,Enum):
    PATIENT = "Patient",
    CLINIC = "Clinic",
    INSURANCE = "Insurance",
    OTHER = "Other"


class RELATIONSHIP(str,Enum):
    SELF = "Self",
    SPOUSE = "Spouse",
    OTHER = "Other",
    CHILD = "Child",
    LIFE_PARTNER = "Life Partner",
    EMPLOYER = "Employer",
    FATHER = "Father",
    GRANDPARENT = "Grandparent",
    MOTHER = "Mother",
    UNKNOWN = "Unknown",
    SIBLING = "Sibling",
    PARENT = "Parent",
    GRANDCHILD = "Grandchild",
    GUARDIAN = "Guardian"

class CONTENT_TYPE(str,Enum):
    BASE64_ENCODED = "Base64 Encoded",
    PLAIN_TEXT = "Plain Text",
    RICH_TEXT = "Rich Text"

class LANGUAGE(str,Enum):
    AF = "af",
    AE = "ae",
    AK = "ak",
    BG = "bg",
    BH = "bh",
    CA = "ca",
    CE = "ce",
    CH = "ch",
    CO = "co",
    CR = "cr",
    CS = "cs",
    CU = "cu",
    CV = "cv",
    DA = "da",
    DZ = "dz",
    EE = "ee",
    EN = "en",
    EO = "eo",
    ET = "et",
    EU = "eu",
    FF = "ff",
    GL = "gl",
    HA = "ha",
    HR = "hr",
    II = "ii",
    IS = "is",
    LU = "lu",
    KK = "kk",
    KN = "kn",
    KU = "ku",
    KV = "kv",
    KW = "kw",
    MK = "mk",
    MS = "ms",
    NB = "nb",
    ND = "nd",
    PI = "pi",
    SK = "sk",
    OM = "om",
    QU = "qu",
    SN = "sn",
    SQ = "sq",
    SU = "su",
    TA = "ta",
    TI = "ti",
    TK = "tk",
    UK = "uk",
    WO = "wo",
    YO = "yo",
    ID = "id",
    IG = "ig",
    JV = "jv",
    KJ = "kj",
    KM = "km",
    LN = "ln",
    LO = "lo",
    MR = "mr",
    MT = "mt",
    NA = "na",
    NG = "ng",
    NO = "no",
    OJ = "oj",
    PT = "pt",
    RM = "rm",
    RW = "rw",
    SG = "sg",
    ST = "st",
    SW = "sw",
    TH = "th",
    TR = "tr",
    TT = "tt",
    UR = "ur",
    VO = "vo",
    ZH = "zh",
    AA = "aa",
    DE = "de",
    FI = "fi",
    HT = "ht",
    HY = "hy",
    IE = "ie",
    IK = "ik",
    KI = "ki",
    KL = "kl",
    KO = "ko",
    KR = "kr",
    KS = "ks",
    KY = "ky",
    LV = "lv",
    MG = "mg",
    MI = "mi",
    ML = "ml",
    MY = "my",
    NE = "ne",
    NL = "nl",
    NY = "ny",
    OC = "oc",
    OS = "os",
    PA = "pa",
    PL = "pl",
    PS = "ps",
    RN = "rn",
    SC = "sc",
    SD = "sd",
    SI = "si",
    SL = "sl",
    SO = "so",
    SR = "sr",
    SV = "sv",
    TG = "tg",
    TL = "tl",
    TN = "tn",
    TO = "to",
    TW = "tw",
    TY = "ty",
    UG = "ug",
    VE = "ve",
    VI = "vi",
    WA = "wa",
    ZA = "za",
    ES = "es",
    FA = "fa",
    GN = "gn",
    HU = "hu",
    HZ = "hz",
    IA = "ia",
    LA = "la",
    LT = "lt",
    MH = "mh",
    MN = "mn",
    NN = "nn",
    NR = "nr",
    NV = "nv",
    OR = "or",
    RO = "ro",
    SA = "sa",
    SE = "se",
    SS = "ss",
    TE = "te",
    TS = "ts",
    UZ = "uz",
    XH = "xh",
    YI = "yi",
    ZU = "zu",
    OT = "Ot",
    UN = "Un",
    AB = "ab",
    AV = "av",
    BA = "ba",
    AM = "am",
    AN = "an",
    AY = "ay",
    AR = "ar",
    AS = "as",
    AZ = "az",
    BE = "be",
    BI = "bi",
    BM = "bm",
    BN = "bn",
    BO = "bo",
    BR = "br",
    BS = "bs",
    CY = "cy",
    DV = "dv",
    EL = "el",
    FJ = "fj",
    FO = "fo",
    FR = "fr",
    FY = "fy",
    GA = "ga",
    GD = "gd",
    GU = "gu",
    GV = "gv",
    HE = "he",
    HI = "hi",
    HO = "ho",
    IO = "io",
    IT = "it",
    IU = "iu",
    JA = "ja",
    KA = "ka",
    KG = "kg",
    LB = "lb",
    LG = "lg",
    LI = "li",
    RU = "ru",
    SM = "sm"


class CITIZENSHIP(str,Enum):
    AMERICAN_SAMOA = "American Samoa",	
    ANGUILLA = "Anguilla",	
    AUSTRIA = "Austria",	
    BAHAMAS = "Bahamas",	
    BARBADOS = "Barbados",	
    BHUTAN = "Bhutan",	
    BOSNIA_AND_HERZEGOVINA = "Bosnia and Herzegovina",	
    AFGHANISTAN = "Afghanistan",	
    ALAND_ISLANDS = "Åland Islands",	
    ALBANIA = "Albania",	
    ANGOLA = "Angola",	
    ANDORRA = "Andorra",	
    ARGENTINA = "Argentina",	
    ARMENIA = "Armenia",	
    BANGLADESH = "Bangladesh",	
    BELGIUM = "Belgium",	
    BENIN = "Benin",	
    EUSTATIUS_AND_SABA = "Bonaire Sint Eustatius and Saba",	
    BOTSWANA = "Botswana",	
    BOUVET_ISLAND = "Bouvet Island",	
    BRITISH_INDIAN_TERRITORY = "British Indian Ocean Territory",	
    BRUNEI_DARUSSALAM = "Brunei Darussalam",	
    BURKINA_FASO = "Burkina Faso",	
    BULGARIA = "Bulgaria",	
    ALGERIA = "Algeria",	
    ANTARCTICA = "Antarctica",	
    ANTIGUA_AND_BARBUDA = "Antigua and Barbuda",	
    ARUBA = "Aruba",	
    AUSTRALIA = "Australia",	
    AZERBAIJAN = "Azerbaijan",	
    BAHRAIN = "Bahrain",	
    BELARUS = "Belarus",	
    BELIZE = "Belize",	
    BERMUDA = "Bermuda",	
    BOLIVIA = "Bolivia (Plurinational State of)",
    BRAZIL = "Brazil",	
    BURUNDI = "Burundi",	
    CAYMAN_ISLANDS = "Cayman Islands",	
    CHINA = "China",	
    COLOMBIA = "Colombia",	
    COOK_ISLANDS = "Cook Islands",	
    CURACAO = "Curaçao",	
    EL_SALVADOR = "El Salvador",	
    CAMBODIA = "Cambodia",	
    CHRIMAS_ISLAND = "Christmas Island",	
    CONGO_DEMOCRATIC = "Congo (the Democratic Republic of the)",
    CROATIA = "Croatia",	
    CZECHIA = "Czechia",	
    DOMINICA = "Dominica",	
    CABO_VERDE = "Cabo Verde",	
    CHAD = "Chad",	
    COCOS = "Cocos (Keeling) Islands",	
    COSTA_RICA = "Costa Rica",	
    DENMARK = "Denmark",	
    DOMINICAN_REPUBLIC = "Dominican Republic",	
    CAMEROON = "Cameroon",	
    CHILE = "Chile",	
    CONGO = "Congo",	
    CYPRUS = "Cyprus",	
    EDUCATOR = "Ecuador",	
    CANADA = "Canada",	
    CENTRAL_AFRICAN_REPUBLIC = "Central African Republic",	
    COMOROS = "Comoros",	
    CUBA = "Cuba",	
    DJIBOUTI = "Djibouti",	
    EGYPT = "Egypt",	
    EQUATORIAL_GUINEA = "Equatorial Guinea",	
    ERITREA = "Eritrea",	
    ESTONIA = "Estonia",	
    ETHIOPIA = "Ethiopia",	
    FALKLAND_ISLANDS = "Falkland Islands[Malvinas]",
    FAROE_ISLANDS = "Faroe Islands",	
    FIJI = "Fiji",	
    FINLAND = "Finland",	
    FRANCE = "France",	
    FRENCH_GUIANA = "French Guiana",	
    FRENCH_POLYNESIA = "French Polynesia",	
    FRENCH_SOUTHERN = "French Southern Territories",	
    GABON = "Gabon",	
    GAMBIA = "Gambia",	
    GEORGIA = "Georgia",	
    GERMANY = "Germany",	
    GHANA = "Ghana",	
    GIBRALTAR = "Gibraltar",	
    GREECE = "Greece",	
    GREENLAND = "Greenland",	
    GRENADA = "Grenada",	
    GUADELOUPE = "Guadeloupe",	
    GUAM = "Guam",	
    GUATEMALA = "Guatemala",	
    GUERNSEY = "Guernsey",	
    GUINEA = "Guinea",	
    GUINEA_BISSAU = "Guinea-Bissau",	
    GUYANA = "Guyana",	
    HAITI = "Haiti",	
    HEARD_ISLAND_AND_MCDONALD_ISLANDS = "Heard Island and McDonald Islands",	
    HOLY_SEE = "Holy See",	
    HONDURAS = "Honduras",	
    HONG_KONG = "Hong Kong",	
    HUNGARY = "Hungary",	
    ICELAND = "Iceland",	
    INDIA = "India",	
    INDONESIA = "Indonesia",	
    IRAN = "Iran (Islamic Republic of)",
    IRAQ = "Iraq",	
    IRELAND = "Ireland",	
    ISLE_OF_MAN = "Isle of Man",	
    ISRAEL = "Israel",	
    ITALY = "Italy",	
    JAMAICA = "Jamaica",	
    JAPAN = "Japan",	
    JERSEY = "Jersey",	
    JORDAN = "Jordan",	
    KAZAKHSTAN = "Kazakhstan",	
    KENYA = "Kenya",	
    KIRIBATI = "Kiribati",	
    KOREA = "Korea (the Republic of)",
    KUWAIT = "Kuwait",	
    KYRGYZSTAN = "Kyrgyzstan",	
    LIECHTENSTEIN = "Liechtenstein",	
    MADAGASCAR = "Madagascar",	
    MALI = "Mali",	
    MAURITIUS = "Mauritius",	
    MONACO = "Monaco",	
    MOZAMBIQUE = "Mozambique",	
    NETHERLANDS = "Netherlands",	
    NIGER = "Niger",	
    DEMOCRATIC_REPUBLIC = "Lao Peoples Democratic Republic",	
    LATVIA = "Latvia",	
    LESOTHO = "Lesotho",	
    MACAO = "Macao",	
    MALTA = "Malta",	
    MAYOTTE = "Mayotte",	
    MOLDOVA = "Moldova (the Republic of)",
    MYANMAR = "Myanmar",	
    NIGERIA = "Nigeria",	
    OMAN = "Oman",	
    LEBANON = "Lebanon",	
    LITHUANIA = "Lithuania",	
    MALAWI = "Malawi",	
    MALDIVES = "Maldives",	
    MAURITANIA = "Mauritania",	
    MONGOLIA = "Mongolia",	
    MOROCCO = "Morocco",	
    NEPAL = "Nepal",	
    NICARAGUA = "Nicaragua",	
    NORTHERN_MARIANA_ISLANDS = "Northern Mariana Islands",	
    LIBERIA = "Liberia",	
    LUXEMBOURG = "Luxembourg",	
    MALAYSIA = "Malaysia",	
    MARTINIQUE = "Martinique",	
    MICRONESIA = "Micronesia (Federated States of)",
    MONTSERRAT = "Montserrat",	
    NAURU = "Nauru",	
    NEW_ZEALAND = "New Zealand",	
    NORFOLK_ISLAND = "Norfolk Island",	
    LIBYA = "Libya",	
    MACEDONIA = "Macedonia (the former Yugoslav Republic of)",
    MARSHALL_ISLANDS = "Marshall Islands",	
    MEXICO = "Mexico",	
    MONTENEGRO = "Montenegro",	
    NAMIBIA = "Namibia",	
    NEW_COLEDONIA = "New Caledonia",	
    NIUE = "Niue",	
    NORWAY = "Norway",	
    PAKISTAN = "Pakistan",	
    PALAU = "Palau",	
    PALESTINE = "Palestine State of",	
    PANAMA = "Panama",	
    PAPUA_NEW_GUINEA = "Papua New Guinea",	
    PARAGUAY = "Paraguay",	
    PERU = "Peru",	
    PHILIPPINES = "Philippines",	
    PITCAIRN = "Pitcairn",	
    POLAND = "Poland",	
    PORTUGAL = "Portugal",	
    QATAR = "Qatar",	
    PUERTO_RICO = "Puerto Rico",	
    REUNION = "Réunion",	
    ROMANIA = "Romania",	
    RUSSIAN_FEDERATION = "Russian Federation",	
    RWANDA = "Rwanda",	
    SAINT_BARTHELEMY = "Saint Barthélemy",	
    SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA= "Saint Helena Ascension and Tristan da Cunha",	
    SAINT_KITTS_AND_NEVIS = "Saint Kitts and Nevis",	
    SAINT_LUCIA = "Saint Lucia",	
    SAINT_MARTIN = "Saint Martin (French part)",
    SAINT_PIERRE_AND_MIQUELON =  "Saint Pierre and Miquelon",	
    SAINT_VINCENT_AND_GRENADINES = "Saint Vincent and the Grenadines",	
    SAMOA = "Samoa",	
    SAN_MARINO = "San Marino",	
    SAO_TOME_AND_PRINCIPE = "Sao Tome and Principe",	
    SAUDI_ARABIA = "Saudi Arabia",	
    SENEGAL = "Senegal",	
    SERBIA = "Serbia",	
    SEYCHELLES = "Seychelles",	
    SIERRA_LEONE = "Sierra Leone",	
    SINGAPORE = "Singapore",	
    SINT_MAARTEN = "Sint Maarten (Dutch part)",
    SLOVAKIA = "Slovakia",	
    SLOVENIA = "Slovenia",	
    SOLOMON_ISLANDS = "Solomon Islands",	
    SOMALIA = "Somalia",	
    SOUTH_AFRICA = "South Africa",	
    SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS = "South Georgia and the South Sandwich Islands",	
    SOUTH_SUDAN = "South Sudan",	
    SPAIN = "Spain",	
    SRI_LANKA = "Sri Lanka",	
    SUDAN = "Sudan",	
    SURINAME = "Suriname",	
    SVALBARD_AND_JAN_MAYEN = "Svalbard and Jan Mayen",	
    SWAZILAND = "Swaziland",	
    SWEDEN = "Sweden",	
    SWITZERLAND = "Switzerland",	
    SYRIAN_ARAB_REPUBLIC = "Syrian Arab Republic",	
    TAJIKISTAN = "Tajikistan",	
    TAIWAN = "Taiwan (Province of China)",
    TIMOR_LESTE = "Timor-Leste",	
    TRINIDAD_AND_TOBAGO = "Trinidad and Tobago",	
    TUVALU = "Tuvalu",	
    URUGUAY = "Uruguay",	
    VERGIN_ISLAND_US = "Virgin Islands (U.S.)",	
    YEMEN = "Yemen",	
    TANZANIA = "Tanzania United Republic of",	
    TURKEY = "Turkey",	
    UKRAINE = "Ukraine",	
    UNITED_STATES_OF_AMERICA = "United States of America",	
    VIET_NAM = "Viet Nam",	
    WESTERN_SAHARA = "Western Sahara",	
    THAILAND = "Thailand",	
    TONGA = "Tonga",	
    TURKS_CAICOS_ISLANDS = "Turks and Caicos Islands",	
    UNITED_STATES_OUTLYING_ISLANDS = "United States Minor Outlying Islands",	
    VENEZUELA = "Venezuela (Bolivarian Republic of)",
    ZIMBABWE = "Zimbabwe",	
    TOGO = "Togo",	
    TUNISIA = "Tunisia",	
    UGANDA = "Uganda",	
    UNITED_ARAB_EMIRATES = "United Arab Emirates",	
    UZBEKISTAN = "Uzbekistan",	
    VERGIN_ISLAND_BRITISH = "Virgin Islands (British)",	
    ZAMBIA = "Zambia",	
    TOKELAU = "Tokelau",	
    TURKMENISTAN = "Turkmenistan",	
    UNITED_KINGDOM_OF_BRITAIN_AND_NORTHERN_IRELAND = "United Kingdom of Great Britain and Northern Ireland",	
    VANUATU = "Vanuatu",	
    WALLS_AND_FUTUNA = "Wallis and Futuna",	
    COTE_DIVOIRE = "Côte dIvoire",	
    KOREA_DEMOCRATIC = "Korea (the Democratic Peoples Republic of)",
    DAY_CARE_PSYCHIATRIC ="Day Care Psychiatric ", 
    COGNITIVE_THERAPY = "Cognitive Therapy", 
    MASSAGE_THERAPY = "Massage Therapy", 
    PULMONARY_REHABILITATION = "Pulmonary Rehabilitation", 
    CARDIAC_REHABILITATION = "Cardiac Rehabilitation", 
    CARDIAC = "Cardiac", 
    GASTROINTESTINAL = "Gastrointestinal", 
    UNKNOWN = "Unknown"


class TRANSACTION_TYPE(str,Enum):
    INSTITUTIONAL = "Institutional",
    PROFESSIONAL = "Professional"

class AGREEMENT_TYPE(str,Enum):
    STANDARD = "Standard",
    UNIFIED = "Unified",
    MATHERNITY = "Maternity"

class CLAIM_TYPE(str,Enum):
    ORIGINAL = "Original", 
    CANCEL = "Cancel", 
    REPLACEMENT = "Replacement"

class BENEFITS_ASSIGNMENT_CODE(str,Enum):
    ASSIGNED = "Assigned",
    ASSIGNED_ON_LAB_ONLY = "Assigned on Lab Only",
    NOT_ASSIGNED = "Not Assigned"

class CREDIT_OR_DEBIT(str, Enum):
    CREDIT = "Credit",
    DEBIT = "Debit"

class PAYMENT_METHOD(str,Enum):
    CHECK = "Check", 
    ACH = "ACH", 
    NON_PAYMENT = "Non-Payment"


class CLAIM_STATUS(str,Enum):
    PROCESSED_AS_PRIMARY = "Processed as Primary",	
    NOT_OUR_CLAIM = "Not Our Claim",	
    PREDETERMINATION_PRICING_ONLY = "Predetermination Pricing Only",	
    PROCESSED_AS_SECONDARY_ADDITIONAL_PAYERS = "Processed as Secondary, Forwarded to Additional Payers",	
    DENIED = "Denied",	
    PROCESSED_AS_SECONDARY = "Processed as Secondary",	
    PROCESSED_AS_TERTIARY = "Processed as Tertiary",	
    REVERSAL_OF_PREVIOUS_PAYMENT = "Reversal of Previous Payment",	
    PROCESSED_AS_PRIMARY_ADDITIONAL_PAYERS = "Processed as Primary, Forwarded to Additional Payers",	
    PROCESSED_AS_TERTIARY_ADDITIONAL_PAYERS = "Processed as Tertiary, Forwarded to Additional Payers"

class ADJUSTMENT_TYPES(str,Enum):
    OTHER_ADJUSTMENTS = "Other adjustments",
    PATIENT_RESPONSIBLITY = "Patient responsibility",
    PAYER_INITIATED_REDUCTIONS = "Payor initiated reductions",
    CONTRACTUAL_OBLIGATIONS = "Contractual obligations"

class ADJUSTMENT_REASON(str,Enum):
    COPAYMENT_AMOUNT = "Co-payment amount", 	
    COINSURANCE_AMOUNT = "Coinsurance amount", 	
    DEDUCTIBLE_AMOUNT = "Deductible amount", 	
    CLAIM_NEGOTIATED_DISCOUNT = "Claim specific negotiated discount", 	
    DENIAL = "Denial"

class VALUE_TYPE(str, Enum):
    ADDRESS = "Address", 
    CODED_ENTRY  = "Coded Entry", 
    DATE = "Date", 
    DATETIME = "DateTime", 
    ENCAPSULATED_DATA = "Encapsulated Data", 
    FORMATTED_TEXT = "Formatted Text", 
    ID = "ID", 
    ID_AND_NAME = "ID And Name", 
    MONEY = "Money", 
    NAME = "Name", 
    NUMERIC = "Numeric", 
    PHONE_NUMBER = "Phone Number", 
    PRICE = "Price", 
    REFERENCE_POINTER = "Reference Pointer", 
    STRING = "String", 
    TIME = "Time", 
    STRUCTURED_NUMERIC = "Structured Numeric"

class FINANCIAL_TRANSACTION_TYPE(str,Enum):
    NO_CHARGE = "No Charge",
    CHARGE = "Charge", 
    CREDIT = "Credit", 
    PAYMENT = "Payment", 
    ADJUSTMENT = "Adjustment"

class CODE_SET(str,Enum):
    ICD_10 = "ICD-10", 
    ICD_9 = "ICD-9", 
    HCPCS = "HCPCS", 
    CPT = "CPT", 
    UNKNOWN = "Unknown"

class DIAGNOSIS_TYPE(str,Enum):
    UNKNOWN = "Unknown", 
    ADMITTING = "Admitting", 
    FINAL = "Final", 
    SELF = "Self", 
    WORKING = "Working", 
    PRINCIPAL = "Principal"

class DIAGNOSIS_CODE_SET(str,Enum):
    ICD_10 = "ICD-10", 
    ICD_9 = "ICD-9", 
    HCPCS = "HCPCS", 
    CPT = "CPT", 
    UNKNOWN = "Unknown"

class OBSERVATION_STATUS(str, Enum):
    PRELIMINARY = "Preliminary", 
    INCOMPLETE = "Incomplete", 
    CORRECTED = "Corrected", 
    FINAL = "Final", 
    UNAVAILABLE = "Unavailable", 
    NONE_SPECIFIED = "None Specified", 
    CANCELED = "Canceled", 
    DELETED = "Deleted", 
    SPECIMEN_IN_LAB = "Specimen in lab"

class ABNORMAL_FLAG(str,Enum):
    NORMAL = "Normal", 	
    LOW = "Low", 	
    VERY_LOW = "Very Low", 	
    HIGH = "High", 	
    VERY_HIGH = "Very High", 	
    ABNORMAL = "Abnormal", 	
    SUSCEPTIBLE = "Susceptible", 	
    RESISTANT = "Resistant", 	
    INTERMEDIATE = "Intermediate", 	
    MODERATELY_SUSCEPTIBLE = "Moderately Susceptible", 	
    VERY_SUSCEPTIBLE = "Very Susceptible", 	
    CRITICALLY_ABNORMAL = "Critically Abnormal", 	
    CRITICALLY_LOW = "Critically Low", 	
    CRITICALLY_HIGH = "Critically High", 	
    NOT_SUSCEPTIBLE = "Not Susceptible", 	
    INCONCLUSIVE = "Inconclusive", 	
    VERY_ABNORMAL = "Very Abnormal"


class MEDIA_AVAILABILITY(str,Enum):
    AVAILABLE = "Available",
    UNAVAILABLE = "Unavailable",
    OBSOLETE =  "Obsolete",
    DELETED = "Deleted",
    CANCELLED = "Cancelled"

class NOTE_STATUS(str,Enum):
    AUTHENTICATED = "Authenticated",
    IN_PROGRESS = "In progress"


class NOTE_AVAILABILITY(str, Enum):

    AVAILABLE = "Available",
    UNAVAILABLE = "Unavailable",
    OBSOLETE = "Obsolete",
    DELETED = "Deleted",
    CANCELLED = "Cancelled"

class ORDER_STATUS(str,Enum):
    RESULTED = "Resulted",
    NEW = "New", 
    CANCEL = "Cancel", 
    UPDATE = "Update"


class ORDER_PRIORITY(str,Enum):
    SATRT = "Stat", 
    ASAP = "ASAP", 
    ROUTINE = "Routine", 
    PROPERATIVE = "Preoperative", 
    TIMING_CRITICAL = "Timing Critical"

class PROCEDURES_CODE_SET(str, Enum):
    NPI = "NPI", 
    LOINC = "LOINC", 
    ICD_10 = "ICD-10", 
    NDC = "NDC", 
    CVX = "CVX", 
    SSN = "SSN", 
    SNOMED_CT = "SNOMED CT", 
    RXNORM = "RxNorm", 
    CPT_4 = "CPT-4", 
    ICD_9 = "ICD-9", 
    HCPCS = "HCPCS", 
    UNKNOWN = "Unknown", 
    ICD_10_CA = "ICD-10-CA"

class DISCHARGE_STATUS_CODE(str,Enum):
    _03 = "03_Skilled Nursing Facility", 
    _04 = "04_Facility that Provides Custodial or Supportive Care", 
    _06 = "06_Home Under Care of an Organized Home Health Service Organization", 
    _21 = "21_Court/Law Enforcement", 
    _30 = "30_Still a patient", 
    _50 = "50_Hospice - Home", 
    _51 = "51_Hospice - Medical Facility", 
    _61 = "61_Hospital-Based Medicare Approved Swing Bed", 
    _70 = "70_Another Type of Health Care Institution (other)", 
    _88 = "88_Federal Health Care Facility (Readmission)", 
    _90 = "90_Inpatient Rehabilitation Facility (Readmission)", 
    _41 = "41_Expired in a Medical Facility", 
    _62 = "62_Inpatient Rehabilitation Facility", 
    _91 = "91_Medicare Certified Long Term Care Hospital (Readmission)", 
    _95 = "95_Another Type of Health Care Institution (Readmission)", 
    _63 = "63_Medicare Certified Long Term Care Hospital", 
    _69 = "69_Designated Disaster Alternate Care Site", 
    _93 = "93_Psychiatric Hospital (Readmission)", 
    _42 = "42_Expired - place unknown", 
    _64 = "64_Nursing Facility Certified under Medicaid", 
    _92 = "92_Nursing Facility Certified Under Medicaid (Readmission)", 
    _94 = "94_Critical Access Hospital (Readmission)", 
    _01 = "01_Home or Self Care", 
    _02 = "02_Short-Term General Hospital for Inpatient Care", 
    _05 = "05_Designated Cancer Center or Children’s Hospital", 
    _07 = "07_Left Against Medical Advice", 
    _09 = "09_Admitted as an Inpatient", 
    _20 = "20_Expired", 
    _40 = "40_Expired at home", 
    _43 = "43_Federal Health Care Facility", 
    _65 = "65_Psychiatric Hospital", 
    _66 = "66_Critical Access Hospital", 
    _81 = "81_Home or Self Care (Readmission)", 
    _82 = "82_Short Term Inpatient Hospital (Readmission)", 
    _83 = "83_Skilled Nursing Facility (SNF) (Readmission)", 
    _84 = "84_Facility that Provides Custodial or Supportive Care (Readmission)", 
    _85 = "85_Designated Cancer Center or Children's Hospital (Readmission)", 
    _86 = "86_Home Under Care of Organized Home Health Service Organization (Readmission)", 
    _87 = "87_Court/Law Enforcement (Readmission)", 
    _89 = "89_Hospital-based Medicare Approved Swing Bed (Readmission)", 
    _0 = "0_unknown"


class REFERRAL_TYPE(str, Enum):
    OTHER = "Other", 
    CONSULTATION = "Consultation", 
    LABORATORY = "Laboratory", 
    RADIOLOGY = "Radiology", 
    MEDICAL = "Medical", 
    SKILLED_NURSING = "Skilled Nursing", 
    HOME_CARE = "Home Care", 
    PSYCHIATRIC = "Psychiatric"

class REFERRAL_CATEGORY(str, Enum):
    OUTPATIENT = "Outpatient", 
    INPATIENT = "Inpatient",
    EMERGENCY = "Emergency",
    AMBULATORY = "Ambulatory"

class REFERRAL_PRIORITY(str , Enum):
    STAT = "STAT", 
    ASAP = "ASAP", 
    ROUTINE = "Routine"

class REFERRAL_STATUS(str, Enum):
    ACCEPTED = "Accepted", 
    PENDING = "Pending", 
    REJECTED = "Rejected", 
    EXPIRED = "Expired", 
    CLOSED = "Closed"

class REFERRAL_REASON(str, Enum):
    PATIENT_PREFERENCE = "Patient Preference", 
    SECOND_OPINION = "Second Opinion", 
    PROVIDER_ORDERED = "Provider Ordered", 
    WORK_LOAD = "Work Load" 

class REFERRAL_SERVICE_LOCATION(str , Enum):
    PHARMACY = "Pharmacy", 
    TELEHEALTH = "Telehealth", 
    SCHOOL = "School", 
    HOMELESS_SHELTER = "Homeless Shelter", 
    INDIAN_HEALTH_SEARVICE_FREE_BASED_FACILITY = "Indian Health Service Free-standing Facility", 
    INDIAN_HEALTH_SEARVICE_PROVIDER_BASED_FACILITY = "Indian Health Service Provider-based Facility", 
    TRIBAL_638_FREE_STANDING_FACILITY = "Tribal 638 Free-standing Facility", 
    TRIBAL_658_PROVIDER_BASED_FACILTY = "Tribal 638 Provider-based Facility", 
    PRISON = "Prison/Correctional Facility", 
    OFFICE = "Office", 
    HOME = "Home", 
    ASSISTED_LIVING_FACILITY = "Assisted Living Facility", 
    GROUP_HOME = "Group Home", 
    MOBILE_UNIT = "Mobile Unit", 
    TEMPORARY_LODGING = "Temporary Lodging", 
    WALK_IN_RETAIL_HEALTH_CLINIC = "Walk-in Retail Health Clinic", 
    WORKSITE = "Place of Employment – Worksite", 
    OFF_CAMPUS_OUTPAITIENT_HOSPITAL = "Off Campus – Outpatient Hospital", 
    URGENT_CARE_FACILITY = "Urgent Care Facility", 
    INPATIENT_HOSPITAL = "Inpatient Hospital", 
    ON_CAMPUS_OUTPAITIENT_HOSPITAL = "On Campus – Outpatient Hospital", 
    EMERGENCY_ROMM_HOSPITAL = "Emergency Room – Hospital", 
    AMBULATORY_SURGICAL_CENTER = "Ambulatory Surgical Center", 
    BIRTHING_CENTER = "Birthing Center", 
    MILITARY_TREATMENT_FACILITY = "Military Treatment Facility", 
    SKILLED_NURSING_FACILITY = "Skilled Nursing Facility", 
    NURSING_FACILITY = "Nursing Facility", 
    CUSTODIAL_CARE_FACILITY = "Custodial Care Facility", 
    HOSPICE = "Hospice", 
    ABULANCE_LAND = "Ambulance – Land", 
    AMBULANCE_AIR_OR_WATER = "Ambulance – Air or Water", 
    INDEPENDENT_CLINIC = "Independent Clinic", 
    FEDERALLY_QUALIFIED_HEALTH_CENTER = "Federally Qualified Health Center", 
    INPATIENT_PSYCHIATRIC_FACILITY = "Inpatient Psychiatric Facility", 
    PSYCHIATRIC_FACILITY_PARTIAL_HOSPITALIZATION = "Psychiatric Facility – Partial Hospitalization", 
    COMMUNITY_HEALTH_CENTER = "Community Mental Health Center", 
    INTERMEDIATE_CARE_FACILITY = "Intermediate Care Facility/Individuals with Intellectual Disabilities", 
    RESIDENTIAL_ABUSE_TREATMENT_FACILITY = "Residential Substance Abuse Treatment Facility", 
    PSYCHIATRIC_RESIDENTIAL_TREATMENT_CENTER = "Psychiatric Residential Treatment Center", 
    NON_RESIDENTIAL_SUBSTANCE_ABUSE_TREATMENT_FACILITY = "Non-residential Substance Abuse Treatment Facility", 
    NON_RESIDENTIAL_OPIOID_TREATMENT_FACILITY = "Non-residential opioid Treatment Facility", 
    MASS_IMMUNIZATION_CENTER = "Mass Immunization Center", 
    COMPREHENSIVE_INPATIENT_REHABILITATION_FACILITY = "Comprehensive Inpatient Rehabilitation Facility", 
    COMPREHENSIVE_OUTPATIENT_REHABILITATION_FACILITY = "Comprehensive Outpatient Rehabilitation Facility", 
    END_STAGE_RENAL_DISEASE_TREATMENT_FACILITY = "End-Stage Renal Disease Treatment Facility", 
    PUBLIC_HEALTH_CLINIC = "Public Health Clinic", 
    RURAL_HEALTH_CLINIC = "Rural Health Clinic", 
    INDEPENDENT_LAB = "Independent Laboratory", 
    OTHER_PLACE_OF_SERVICE = "Other Place of Service"

class REFERRAL_REQUEST_TYPE(str, Enum):
    INITIAL = "Initial", 
    EXTENSION = "Extension", 
    REVISED = "Revised", 
    RENEWAL = "Renewal", 
    RECONSIDERAtion = "Reconsideration", 
    CANCEL = "Cancel", 
    APPEAL = "Appeal"

class REFERRAL_RELATED_CAUSE(str,Enum):
    ACCIDENT = "Accident", 
    EMPLOYMENT = "Employment", 
    ANOTHER_PARTY = "Another Party"

class AUTHORIZATION_TYPE(str, Enum):
    INSTITUTIONAL = "Institutional", 
    PROFESSIONAL = "Professional"

class AUTHORIZATION_CATEGORY(str,Enum):
    ADMISSSION = "Admission", 
    PROCEDURE = "Procedure", 
    REFERRAL = "Referral", 
    SPECIALTY_CARE = "Specialty Care"


class AUTHORIZATION_CERTIFICATION_CDOE(str, Enum):
    INITIAL = "Initial", 
    EXTENSION = "Extension", 
    REVISED = "Revised", 
    RENEWAL = "Renewal", 
    RECONSIDERATION = "Reconsideration", 
    CANCEL = "Cancel", 
    APPEAL = "Appeal"

class AUTHORIZATION_SERVICE_TYPE(str, Enum):
    MEDICAL_CARE = "Medical care", 
    SURGICAL = "Surgical", 
    CONSULTATION = "Consultation", 
    DIAGNOSTIC_X_RAY = "Diagnostic X-Ray", 
    DIAGNOSTIC_LAB = "Diagnostic Lab", 
    RADIATION_THERAPY = "Radiation Therapy", 
    ANESTHESIA = "Anesthesia", 
    SURGICAL_ASSISTANCE = "Surgical Assistance", 
    USED_DURABLE_MEDICAL_EQUIPMENT = "Used Durable Medical Equipment", 
    DURABLE_MEDICAL_EQUIPMENT_PURCHASE = "Durable Medical Equipment purchase", 
    RENAL_SUPPLIES_IN_HOME = "Renal supplies in the home", 
    ALTERNATE_METHOD_DIALYSIS = "Alternate method dialysis", 
    CHRONIC_RENAL_DISEASE_EQUIPMENT = "Chronic renal disease equipment", 
    PRE_ADMISSION_TESTING = "Pre Admission Testing", 
    DURABLE_MEDICAL_EQUIPMENT_RENTAL = "Durable Medical Equipment rental", 
    SECOND_SURGICAL_OPINION = "Second surgical opinion", 
    THIRD_SURGICAL_OPINION = "Third surgical opinion", 
    DIAGNOSTIC_DENTAL = "Diagnostic Dental", 
    RESTORATIVE = "Restorative", 
    ENDODONTICS = "Endodontics", 
    MAXILLOFACIAL_PROSTHETICS = "Maxillofacial Prosthetics", 
    ADJUNCTIVE_DENTAL_SERVICES = "Adjunctive Dental Services", 
    CHIROPRACTIC  = "Chiropractic", 
    DENTAl_CARE = "Dental Care", 
    DENTAL_CROWNS = "Dental Crowns", 
    DENTAL_ACCIDENT = "Dental Accident", 
    ORTHODONTICS = "Orthodontics", 
    PROSTHODONTICS = "Prosthodontics", 
    ORAL_SURGERY = "Oral surgery", 
    HOME_HEALTH_CARE = "Home Health Care", 
    HOME_HEALTH_VISITS = "Home Health Visits", 
    HOSPICE = "Hospice", 
    RESPITE_CARE = "Respite care", 
    LONG_TERN_CARE = "Long Term Care", 
    MEDICALLY_RELATED_TRANSPORTATION = "Medically Related Transportation", 
    IN_VITRO_FERTILIZATION = "In Vitro Fertilization", 
    MRI_CAT_SCAN = "MRI/CAT scan", 
    DONOR_PROCEDURES = "Donor Procedures", 
    ACUPUNCTURE = "Acupuncture", 
    NEWBORN_CARE = "Newborn care", 
    PATHOLOGY = "Pathology", 
    SMOKING_CESSATION = "Smoking Cessation", 
    WELL_BABY_CARE = "Well Baby Care", 
    MATERNITY = "Maternity", 
    TRANSPLANTS = "Transplants", 
    AUDIOLOGY_EXAM = "Audiology Exam", 
    INHALATION_THERAPY = "Inhalation Therapy", 
    DIAGNOSTIC_MEDICAL = "Diagnostic Medical", 
    PRIVATE_DUTY_NURSING = "Private Duty Nursing", 
    PROSTHWTIC_DEVICE = "Prosthetic Device", 
    DIALYSIS = "Dialysis", 
    OTOLOGICAL_EXAM = "Otological Exam", 
    CHEMOTHERAPY = "Chemotherapy", 
    ALLERGY_TESTING = "Allergy Testing", 
    IMMUNIZATIONS = "Immunizations", 
    FAMILY_PLANNING = "Family Planning", 
    INFERTILITY = "Infertility", 
    ABORTION = "Abortion", 
    AIDS = "AIDS", 
    EMERGENCY_SERVICES = "Emergency Services", 
    CANCER = "Cancer", 
    PHARMACY = "Pharmacy", 
    PODIATRY = "Podiatry", 
    PSYCHIATRIC = "Psychiatric", 
    PSYCHOTHERAPY = "Psychotherapy", 
    REHABILITATION = "Rehabilitation", 
    OCCUPATIONAL_THERAPY = "Occupational Therapy", 
    PHYSICAL_MEDICINE = "Physical Medicine", 
    SPEECH_THERAPY = "Speech Therapy", 
    SKILLED_NURSING_CARE = "Skilled Nursing Care", 
    SKILLED_NURSING_CAREROOM_AND_BOARD = "Skilled Nursing Care-Room and Board", 
    ALCOHOLISM = "Alcoholism", 
    DRUG_ADDICTION = "Drug Addiction", 
    VISION_OPTOMETRY = "Vision Optometry", 
    EXPERIMENTAL_DRUG_THERAPY = "Experimental Drug Therapy", 
    BURN_CARE = "Burn Care", 
    PARTIAL_HOSPITALIZATION = "Partial Hospitalization(psychiatric)", 
    DAY_CARE_PSYCHIATRIC = "Day Care Psychiatric ", 
    COGNITIVE_THERAPY = "Cognitive Therapy", 
    MASSAGE_THERAPY = "Massage Therapy", 
    PULMONARY_REHABILITATION = "Pulmonary Rehabilitation", 
    CARDIAC_REHABILITATION = "Cardiac Rehabilitation", 
    CARDIAC = "Cardiac", 
    GASTROINTESTINAL = "Gastrointestinal", 
    ENDOCRINE = "Endocrine", 
    NEUROLOGY = "Neurology", 
    INVASIVE_PROCEDURES = "Invasive Procedures", 
    PHYSICIAN_SICK_VISIT = "Physician Sick Visit", 
    PHYSICIAN_WELL_VISIT = "Physician Well Visit", 
    CORONARY_CARE = "Coronary Care", 
    CASE_MANAGEMENT = "Case Management", 
    ALLERGY = "Allergy", 
    INTENSIVE_CARE = "Intensive Care", 
    MENTAL_HEALTH = "Mental Health", 
    NEONATAL_INTENSIVE_CARE = "Neonatal Intensive Care", 
    ONOCOLOGY = "Oncology", 
    PHYSICAL_THERAPY = "Physical Therapy", 
    PULMONARY = "Pulmonary ", 
    RENAL = "Renal", 
    RESIDENTIAL_PSYCHIATRIC_TREATMENT = "Residential Psychiatric Treatment", 
    TRANSITIONAL_CARE = "Transitional Care", 
    TRANSITIONAL_NURSERY_CARE = "Transitional Nursery Care", 
    SUBSTANCE_ABUSE_REHABILITATION = "Substance Abuse Rehabilitation"

class AUTHORIZATION_SERVICE_LEVEL(str , Enum):
    ELECTIVE = "Elective", 
    EMERGENCY = "Emergency", 
    URGENT = "Urgent"

class ADMISSION_SOURCE(str, Enum):
    NON_HEALTHFACILITY = "Non-Health Facility", 
    CLINIC = "Clinic", 
    TRANSFER_FROM_ANOTHER_HOSPITAL = "Transfer From Another Hospital", 
    TRANSFER_FROM_SNF_TO_ICF = "Transfer From SNF or ICF", 
    TRANSFER_FROM_ANOTHER_HEALTH_CARE_FACILITY = "Transfer From Another Health Care Facility", 
    EMERGENCY_ROOM = "Emergency Room", 
    LAW_ENFORCEMENT = "Law Enforcement", 
    TRANSFER_FROM_AMBULATORY_SURGERY_CENTER = "Transfer From Ambulatory Surgery Center", 
    TRANSFER_FROM_HOSPITAL = "Transfer From Hospice", 
    UNKNOWN = "Unknown"

class ADMISSION_TYPE(str,Enum):
    IMMEDIATE_ATTENTION_DUETO_PATIOENT_CONDITION = "Immediate Attention Due To Patient Condition", 
    UNKNOWN = "Unknown", 
    IMMEDIATE_ATTENTION_DUETO_PHYSICALORMENTAL_DISORDER = "Immediate Attention Due To Physical or Mental Disorder", 
    SCHEDULED_ADMISSION = "Scheduled Admission", 
    SPECIAL_CIRCUMSTANCES = "Special Circumstances", 
    TRAUMA = "Trauma", 
    UNDEFINED = "Undefined"

class DATE_TYPE(str, Enum):
    ESTIMATED_BIRTH = "Estimated Birth", 
    EVENT = "Event", 
    LAST_MENSTRUAL_PERIOD = "Last Menstrual Period", 
    DISCHARGE = "Discharge", 
    EFFECTIVE = "Effective", 
    EXPIRATION = "Expiration", 
    ILLNESS_ONSET = "Illness Onset",
    ISSUE = "Issue",
    SERVICE = "Service",
    ACCIDENT = "Accident",
    ADMISSION = "Admission",
    INITIAL_TREATMWNT = "Initial Treatment",
    LAST_VISIT = "Last Visit",
    LAST_XRAY = "Last X-Ray",
    PRESCRIPTION = "Prescription",
    STATEMENT = "Statement"

class PROVIDER_TYPE(str,Enum):
    ASSISTANT_SURGEON = "Assistant Surgeon", 
    REFERRING_PROVIDER = "Referring Provider", 
    OTHER = "Other", 
    PATIENT_PCP = "Patient PCP", 
    SERVICE_PROVIDER = "Service Provider", 
    ATTENDING_PROVIDER = "Attending Provider", 
    RENDERING_PROVIDER = "Rendering Provider", 
    OPERATING_PHYSICIAN = "Operating Physician", 
    SERVICE_LOCATION = "Service Location", 
    CLINIC = "Clinic", 
    OTHER_PHYSICIAN = "Other Physician", 
    PROVIDER = "Provider", 
    FACILITY = "Facility", 
    PHYSICIAN_CLINIC_GROUP_PRACTICE = "Physician, Clinic or Group Practice", 
    PURCHASE_SERVICE_PROVIDER = "Purchase Service Provider", 
    GRUOP_PRACTICE = "Group Practice", 
    ORDERING_PHYSICIAN = "Ordering Physician", 
    SUPERVISING_PHYSICIAN = "Supervising Physician"

class STUDY_TYPE(str,Enum):
    INTERVENTIONAL = "Interventional", 
    OBSERVATIONAL = "Observational", 
    EXPANDED_ACCESS = "Expanded Access"


class SUBJETCT_STATUS(str, Enum):
    ON_STUDY = "on-study", 
    OFF_STUDY = "off-study", 
    ON_STUDY_INTERVENTION = "on-study-intervention", 
    FOLLOW_UP = "follow-up", 
    COMPLETED = "completed", 
    INTELIGIBLE = "ineligible", 
    FOLLOW_UP_LONG_TERM = "follow-up-long-term"

class VISIT_STATUS(str, Enum):
    PENDING = "Pending", 
    OTHER = "Other", 
    SCHEDULED = "Scheduled", 
    ARRIVED = "Arrived", 
    COMPLETED = "Completed", 
    NO_SHOW = "No Show", 
    CANCELED = "Canceled", 
    LEFT_WITHOUT_BEING_SEEN = "Left Without Being Seen", 
    RESCHEDULED = "Rescheduled"
